name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  rspec:
    name: rspec - ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2
          - 3.3
          - 3.4
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bin/setup
      - run: bin/rake appraisal spec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: bin/setup
      - run: bin/rake rubocop
